[tool.poetry]
name = "spark-data-aggregation"
version = "0.1.0"
description = ""
authors = ["ErRahul9 <rparashar@mountain.com>"]
readme = "README.md"
packages = [{include = "spark_data_aggregation"}]

[tool.poetry.dependencies]
python = "^3.11"
pyspark = "^3.5.4"
boto3 = "^1.35.90"
databricks = "^0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
